### ISSUE TITLE
Add search bar to members page

### ISSUE THREAD

**Issue by KrashLeviathan** [ISU-WebDevClub/wdc-website#7]
As we add members, that page is going to fill up, and it will be difficult to find a specific person. Especially since the algorithm orders the grid in a random fashion every time (so no one always gets prime real estate at the top). As the person uses the search bar, it should filter out non-matches intelligently as they type.

[Migrated from club-website repo](https://github.com/ISU-WebDevClub/club-website/issues/49)

**Comment by frostbyte100** [comment]
@KrashLeviathan Don't think we should implement this quite yet
